name: Deploy Vite App to GitHub Pages

# Evento que activa la ejecución del flujo de trabajo
on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal
  # Permitir ejecución manual
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # O la versión de Node.js que uses en tu proyecto

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
